tap "caskroom/cask"
tap "caskroom/versions"
tap "facebook/fb"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
tap "neovim/neovim"

brew "brew-cask"

cask "alfred"
cask "amethyst"
cask "charles"
cask "chromedriver"
cask "cyberduck"
cask "docker"
cask "dropbox"
